# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "puphpet/debian75-x64"

  config.vm.define "web" do |web|
    web.vm.provision :shell, path: "update_and_install_apache.sh", privileged: true
    web.vm.network "private_network", ip: "192.168.0.2"
  end

  config.vm.define "db" do |db|
    db.vm.provision :shell, path: "install_mysql.sh", privileged: true
    db.vm.network "private_network", ip: "192.168.0.3"
  end
end
